[package]
name = "union-test"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
voyager-sdk = { workspace = true }
unionlabs = { workspace = true }
serde = { workspace = true }
cosmos-client      = { workspace = true }
concurrent-keyring = { workspace = true }
protos             = { workspace = true }
tokio              = { workspace = true }
hex-literal = { workspace = true }
ibc-union-msg = { workspace = true }
trusted-mpt-light-client-types = { workspace = true, features = ["serde", "bincode", "ethabi"]}

alloy              = { workspace = true, features = ["contract", "network", "providers", "signers", "signer-local", "rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "provider-ws"] }
bip32              = { workspace = true }
ibc-union-spec = { workspace = true }
ibc-solidity   = { workspace = true, features = ["serde", "rpc"] }

[lints]
workspace = true
