[package]
name = "rustfmt-sort"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
syn = { version = "*", features = ["full", "visit-mut", "extra-traits", "printing"] }
quote = "1.0.40"
