[package]
name    = "on-zkgm-call-proxy"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
cosmwasm-std = { workspace = true, features = ["abort"] }
embed-commit = { workspace = true }
frissitheto  = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
thiserror    = { workspace = true }
