[package]
name    = "on-zkgm-call-proxy"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
cosmwasm-schema      = { workspace = true }
cosmwasm-std         = { workspace = true }
embed-commit         = { workspace = true }
frissitheto          = { workspace = true }
ibc-union-spec       = { workspace = true, features = ["serde"] }
serde                = { workspace = true, features = ["derive"] }
serde-json-wasm      = "1.0"
thiserror            = { workspace = true }
unionlabs-primitives = { workspace = true, features = ["serde"] }

[dev-dependencies]
hex-literal = { workspace = true }
