[package]
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
name    = "zkgm"
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
ibc = { local = "../ibc" }

[addresses]
# ibc      = "0x25763a037769c4783ee2414110302b69b52060c87cf763a4fae56337b296c4f3"
# zkgm     = "0x0"
#
ibc  = "_"
zkgm = "_"

[dev-addresses]
ibc  = "0x22222"
zkgm = "0x4444444444444"
