[package]
name    = "json-schema-to-nixos-module-options"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
embed-commit = { workspace = true }
schemars     = { workspace = true }
serde_json   = { workspace = true }
