[package]
name    = "ibc-union-msg"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[features]
cw-orch-interface = ["schemars", "dep:cw-orch", "dep:cosmwasm-std", "dep:cosmwasm-schema"]
schemars          = ["dep:schemars", "unionlabs-primitives/schemars", "ibc-union-spec/schemars"]

[dependencies]
ibc-union-spec       = { workspace = true, features = ["serde"] }
serde                = { workspace = true, features = ["derive"] }
unionlabs-primitives = { workspace = true, features = ["serde"] }

cosmwasm-schema = { workspace = true, optional = true }
cosmwasm-std    = { workspace = true, optional = true }
cw-orch         = { workspace = true, optional = true }
schemars        = { workspace = true, optional = true }
