[package]
name    = "voyager-client-module-parlia"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
embed-commit                = { workspace = true }
ethereum-light-client-types = { workspace = true, features = ["serde", "bincode"] }
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
parlia-light-client-types   = { workspace = true, features = ["serde", "bincode", "ethabi"] }
serde                       = { workspace = true, features = ["derive"] }
serde_json                  = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
unionlabs                   = { workspace = true }
voyager-sdk                 = { workspace = true }
