[package]
name    = "osmosis-tokenfactory-token-owner"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std                      = { workspace = true }
osmosis-tokenfactory-token-minter = { workspace = true }
token-factory-api                 = { workspace = true }

[lints]
workspace = true
