name: Deploy App 2

on:
  push:
    branches:
      - main
      - release/app2
    paths:
      - 'app2/**'
  pull_request:
    paths:
      - 'app2/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: '--no-warnings'
  ACTIONS_RUNNER_DEBUG: true

jobs:
  garnix:
    name: Wait on Garnix CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait on Garnix CI Check Suite
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          REF: ${{ github.head_ref || github.sha }}
        run: |
          exit 0
          sleep 16

          check_suites=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$REPO/commits/$REF/check-suites")

          url=$(echo $check_suites | jq -r '.check_suites | .[] | select(.app.name == "Garnix CI") | .check_runs_url')

          status=''

          while [[ $status != 'completed' ]]; do
            sleep 16
            app2_run=$(curl --silent "$url" | jq '.check_runs | .[] | select(.name == "package app2 [x86_64-linux]")')

            status=$(echo $app2_run | jq -r '.status')
          done

          conclusion=$(echo $app2_run | jq '.conclusion')
          case "$conclusion" in
            failure | timed_out | action_required | stale | startup_failure)
              echo "ERROR: Garnix CI concluded with $conclusion"
              exit 1
              ;;
            *)
              echo "INFO: Garnix CI concluded with $conclusion"
              ;;
          esac

  deploy-preview:
    needs: ['garnix']
    runs-on: ['ubuntu-latest']
    permissions:
      contents: read
      pull-requests: write
    env:
      npm_config_yes: true
      ENVIRONMENT: 'preview'
    environment: 'app2-preview'
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= union.cachix.org-1:TV9o8jexzNVbM1VNBOq9fu8NK+hL6ZhOyOh0quATy+M=
            trusted-substituters = https://cache.nixos.org https://union.cachix.org
      - name: Fetch from Cache
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        run: |
          nix build .#app2
      - name: '[preview] 🔶 Publish to Cloudflare Pages'
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
        run: npx --yes wrangler@latest pages --project-name="app2" deploy result >> /tmp/app2_deploy.txt

      - name: Set Deploy Output
        run: |
          {
            echo 'DEPLOY_OUTPUT<<EOF'
            tail -n 2 /tmp/app2_deploy.txt
            echo 'EOF'
          } >> $GITHUB_ENV

      - name: Comment Site Deploy Results
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # App 2 🤌
            ${{ env.DEPLOY_OUTPUT }}

            **${{ env.LAST_UPDATED_AT }}**
          comment_tag: deploy-app2-preview-result

  deploy-manual:
    runs-on: ['ubuntu-latest']
    env:
      npm_config_yes: true
      ENVIRONMENT: 'preview'
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= union.cachix.org-1:TV9o8jexzNVbM1VNBOq9fu8NK+hL6ZhOyOh0quATy+M=
            trusted-substituters = https://cache.nixos.org https://cache.garnix.io https://union.cachix.org
      - name: Fetch from Cache
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        run: |
          nix build .#app2
      - name: '[workflow-dispatch] 🔶 Publish to Cloudflare Pages'
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
        run: npx --yes wrangler@latest pages --project-name="app2" deploy result

  deploy-staging:
    needs: ['garnix']
    runs-on: ['ubuntu-latest']
    env:
      npm_config_yes: true
      ENVIRONMENT: 'staging'
    environment: 'app2-staging'
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= union.cachix.org-1:TV9o8jexzNVbM1VNBOq9fu8NK+hL6ZhOyOh0quATy+M=
            trusted-substituters = https://cache.nixos.org https://cache.garnix.io https://union.cachix.org
      - name: Fetch from Cache
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        run: |
          nix build .#app2
      - name: '[staging] 🔶 Publish to Cloudflare Pages'
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
        run: npx --yes wrangler@latest pages --project-name="app2" --branch="staging" deploy result

  deploy-production:
    needs: ['garnix']
    runs-on: ['ubuntu-latest']
    env:
      npm_config_yes: true
      ENVIRONMENT: 'production'
    environment: 'app2-production'
    if: github.event_name == 'push' && github.ref == 'refs/heads/release/app2'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= union.cachix.org-1:TV9o8jexzNVbM1VNBOq9fu8NK+hL6ZhOyOh0quATy+M=
            trusted-substituters = https://cache.nixos.org https://cache.garnix.io https://union.cachix.org
      - name: Fetch from Cache
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        run: |
          nix build .#app2
      - name: '[production] 🔶 Publish to Cloudflare Pages'
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
        run: npx --yes wrangler@latest pages --project-name="app2" --branch="main" deploy result

