name: Garnix Test

on:
  push:

jobs:
  garnix:
    name: Wait on Garnix CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait on Garnix CI Check Suite
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          REF: ${{ github.head_ref || github.sha }}
        run: |
          sleep 15

          status=''

          while [[ $status != 'completed' ]]; do
            check_suites=$(gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/repos/$REPO/commits/$REF/check-suites")

            echo $check_suites | jq .
